//
//	UIDashedLine.h
//	New Image
//
//	Created by Nor Sanavongsay on 10/8/11
//	Copyright 2011 nawDsign
//	This code was generated by Opacity. You may use or modify it in any way.
//

#import <UIKit/UIKit.h>

extern const CGFloat kMyViewWidth;
extern const CGFloat kMyViewHeight;

@interface MyView : UIView

@end
