//
//	UILocationIconImage.h
//	New Image
//
//	Created by Nor Sanavongsay on 10/25/11
//	Copyright 2011 nawDsign
//	This code was generated by Opacity. You may use or modify it in any way.
//

#import <UIKit/UIKit.h>

extern const CGFloat kUILocationIconImageWidth;
extern const CGFloat kUILocationIconImageHeight;

@interface UILocationIconImage : UIView

@end
