//
//	UIOverlay.h
//	New Image
//
//	Created by Nor Sanavongsay on 10/6/11
//	Copyright 2011 nawDsign
//	This code was generated by Opacity. You may use or modify it in any way.
//

#import <UIKit/UIKit.h>

extern const CGFloat kUIOverlayWidth;
extern const CGFloat kUIOverlayHeight;

@interface UIOverlay : UIView

@end
